# Generated by Django 4.2.11 on 2024-04-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_item_text_alter_item_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
    ]
