# Generated by Django 4.2.11 on 2024-04-18 01:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
